#!/usr/bin/env node
// scripts/generate-skills.mjs
// Bundles agents/skills/*.md and agents/brands/*.md into typed records
// so Workers (and GitHub Actions scripts) can load them without fs at
// request time. Markdown under agents/ remains the source of truth.

import { readdirSync, readFileSync, writeFileSync, mkdirSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const SKILLS_DIR = join(ROOT, "agents", "skills");
const BRANDS_DIR = join(ROOT, "agents", "brands");
const OUT_TS = join(ROOT, "src", "lib", "agents", "generated.ts");
const OUT_MJS = join(ROOT, "scripts", "agents", "generated-skills.mjs");

function loadDir(dir) {
  /** @type {Record<string, string>} */
  const out = {};
  for (const name of readdirSync(dir)) {
    if (!name.endsWith(".md")) continue;
    const key = name.slice(0, -3);
    out[key] = readFileSync(join(dir, name), "utf8");
  }
  return out;
}

function escapeTemplate(s) {
  return s.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");
}

function toRecordLiteral(obj) {
  const entries = Object.keys(obj)
    .sort()
    .map((k) => `  ${JSON.stringify(k)}: \`${escapeTemplate(obj[k])}\``);
  return `{\n${entries.join(",\n")}\n}`;
}

const skills = loadDir(SKILLS_DIR);
const brands = loadDir(BRANDS_DIR);

const skillKeys = Object.keys(skills).sort();
const brandKeys = Object.keys(brands).sort();

const ts = `// AUTO-GENERATED by scripts/generate-skills.mjs — do not edit by hand.
// Source of truth: agents/skills/*.md and agents/brands/*.md

export const SKILLS = ${toRecordLiteral(skills)} as const;

export type SkillName = keyof typeof SKILLS;

export const BRAND_OVERLAYS = ${toRecordLiteral(brands)} as const;

export type BrandOverlayName = keyof typeof BRAND_OVERLAYS;
`;

const mjs = `// AUTO-GENERATED by scripts/generate-skills.mjs — do not edit by hand.
// Source of truth: agents/skills/*.md and agents/brands/*.md

export const SKILLS = ${toRecordLiteral(skills)};

export const BRAND_OVERLAYS = ${toRecordLiteral(brands)};
`;

mkdirSync(dirname(OUT_TS), { recursive: true });
mkdirSync(dirname(OUT_MJS), { recursive: true });
writeFileSync(OUT_TS, ts, "utf8");
writeFileSync(OUT_MJS, mjs, "utf8");

console.log(
  `generate-skills: ${skillKeys.length} skill(s), ${brandKeys.length} brand overlay(s) → generated.ts + generated-skills.mjs`,
);
